# Generated by Django 2.2.7 on 2019-11-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
